default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['MESSENGER_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: messenger_development

test:
  <<: *default
  database: messenger_test

production:
  <<: *default
  database: messenger_production
